// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// raw_to_datetime
Datetime raw_to_datetime(RawVector src);
RcppExport SEXP _heyexr_raw_to_datetime(SEXP srcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type src(srcSEXP);
    rcpp_result_gen = Rcpp::wrap(raw_to_datetime(src));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_heyexr_raw_to_datetime", (DL_FUNC) &_heyexr_raw_to_datetime, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_heyexr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
