#' Import the CSV produced by "Thickness Analysis" in OCT Explorer
#'
#' Imports and formats the CSV data produced by the "Thickness Analysis"
#' performed by OCT Explorer software.
#'
#' @param csv_file the CSV file to import
#' @param scrub a string to remove from the file column generated by OCT Explorer
#' @param stat the statistic to extract. NOT CURRENTLY IMPLEMENTED
#'
#' @export
#' @importFrom magrittr %>%
#' @importFrom dplyr mutate filter select inner_join
#' @importFrom tidyr gather separate
#' @importFrom stringr str_replace_all
import_thickness_csv <- function(csv_file, scrub, stat="mean") {
    result <- read.delim(csv_file, sep=",", header=TRUE) %>%
        tbl_df %>%
        (function(x) x %>% select(-ncol(x))) %>%
        gather(key=key, value=um, matches("Thickness")) %>%
        mutate(key_stat=ifelse(grepl(key, pattern="Mean"), "mean","sd"),
                      key=gsub(key,
                               pattern="^MeanThickness_|^SDThickness_",
                               replacement="", perl = TRUE))

    result_mean <- result %>%
        filter(key_stat == "mean")

    result_sd <- result %>%
        filter(key_stat == "sd")

    result <- inner_join(result_mean, result_sd)

#         mutate(sample = str_replace_all(Surfaces,
#                                         pattern = scrub,
#                                         replacement = ""))  %>%
#         separate(sample, c("sample_id", "xml_file"), sep="\\\\") %>%
#         select(-Surfaces) %>%
#         mutate(key=gsub(key, pattern="_um$", replacement="", perl = TRUE)) %>%
#         separate(key, c("span","etdrs_region"), sep="_Region", remove=FALSE) %>%
#         separate(span, c("inner_layer","outer_layer"), sep="~", remove=FALSE) %>%
#         mutate(etdrs_region=as.numeric(as.character(etdrs_region)))
#         inner_join(layer_map) %>%
#         select(layer, etdrs_region, um, sample_id)

    return(result)
}
