# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' raw_to_datetime
#' @description
#' Covert the binary representation of Windows filetime to POSIXct
#'
#' @param x a raw vector of 8 bytes representing the number of 100 nanosecond
#' units since 1601-01-01.
#'
#'
#' @details
#' \code{raw_to_datetime} takes an raw vector encoding a 64-bit unsigned integer
#' This value is the number of 100 nanoseconds since 1601-01-01.
#'
#' @export
raw_to_datetime <- function(src) {
    .Call(`_heyexr_raw_to_datetime`, src)
}

