#' Read "grid center" XML file generated by the Iowa Reference Algorithms
#'
#' Reads the coordinates of the grid center as output by the Iowa Reference
#' Algorithms (XML format).
#'
#' @param center_file path to the XML file containing the grid center coordinates
#'
#' @return a list containing the x and y coordinates of the grid center
#'
#' @export
#' @importFrom XML xmlParse xmlRoot xmlValue
#' @importFrom magrittr %>%
read_center_xml <- function(center_file) {
    # TASK: Add documentation above

    oct_center_xml = xmlParse(center_file)

    parsed_center <- list()

    parsed_center[["center"]][["x"]] <-
        xmlRoot(oct_center_xml)[["center"]][["x"]] %>%
        xmlValue %>% as.numeric()
    parsed_center[["center"]][["z"]] <-
        xmlRoot(oct_center_xml)[["center"]][["z"]] %>%
        xmlValue %>% as.numeric()

    # TASK: Parse the rest of the values in the XML file

    return(parsed_center)
}
